logging:
  type: syslog
  level: log_debug

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage


libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

block_cache:
  block-size-mb: 32
  prefetch: 100
  parallelism: 256
  disk-size-mb: 600000
  path: /blobfuse/cache/annotated

attr_cache:
  timeout-sec: 7200

azstorage:
  type: adls
  account-name: avtmdataopssaenrictst001
  account-key: ohYmnxJg8I8QjGu8GRZL6VyWmvedNo5HRd4gd1uOe7PnYJr9UJhvORtIO8RJMCExfTOLEl1BQ3QP+AStdK65og==
  endpoint: https://avtmdataopssaenrictst001.blob.core.windows.net #https://avtmdataopssaenrictst001.dfs.core.windows.net
  mode: key
  container: annotated