name: Deploy Pipeline 2

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Enter the prefix'
        required: false
        type: string
      stamp:
        description: 'Enter a stamp'
        required: false
        type: string
      envType:
        description: 'Select an environment type'
        required: false
        default: 'd'
        type: choice
        options: [d, s, p]
      region:
        description: 'Select a region'
        required: false
        default: 'japaneast'
        type: choice
        options: [us-east-1, us-west-1, eu-central-1, ap-south-1, japaneast]

jobs:
  deploy-raw:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login using managed identity
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install jq (only for Windows runners)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          choco install jq

      - name: Merge runtime parameters with .bicepparam
        id: genparams
        shell: bash
        run: |
          DEFAULT_FILE="infra/main_dev.bicepparam"
          OUTPUT_FILE="infra/merged_params.json"

          cp $DEFAULT_FILE $OUTPUT_FILE

          if [ -n "${{ github.event.inputs.prefix }}" ]; then
            jq --arg val "${{ github.event.inputs.prefix }}" '.parameters.prefix.value = $val' $OUTPUT_FILE > tmp && mv tmp $OUTPUT_FILE
          fi

          if [ -n "${{ github.event.inputs.stamp }}" ]; then
            jq --arg val "${{ github.event.inputs.stamp }}" '.parameters.stamp.value = $val' $OUTPUT_FILE > tmp && mv tmp $OUTPUT_FILE
          fi

          if [ -n "${{ github.event.inputs.envType }}" ]; then
            jq --arg val "${{ github.event.inputs.envType }}" '.parameters.envType.value = $val' $OUTPUT_FILE > tmp && mv tmp $OUTPUT_FILE
          fi

          echo "file=$OUTPUT_FILE" >> $GITHUB_OUTPUT

      - name: Deploy Bicep Template (raw + derived +)
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: RawDerivedDeployment
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: github-cicd
          template-file: infra/main_dev.bicep
          parameters-file: ${{ steps.genparams.outputs.file }}
