name: Deploy Storage Account with Bicep (Windows Self-hosted)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login with Managed Identity
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep Template
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: StorageDeployment
          location: eastus
          scope: resourceGroup
          resource-group-name: github-cicd
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: infra/storageaccount.bicep
          parameters: |
            {
              "storageAccountName": {
                "value": "storagedemo15mpsw3"
              },
              "location": {
                "value": "eastus"
              }
            }
