name: Deploy Raw+Derived Storage Account

on:
  workflow_dispatch:

jobs:
  deploy-raw:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure login using managed identity
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Replace secrets in .bicepparam
        run: |
          export TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
          export SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          envsubst < infra/main_dev.bicepparam.template > infra/main_dev.bicepparam

      - name: Deploy Bicep Template (raw + derived +)
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: RawDerivedDeployment
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: github-cicd
          template-file: infra/main_dev.bicep
          parameters-file: infra/main_dev.bicepparam

